[tool.mypy]
files = "."
ignore_missing_imports = true

[tool.ruff.lint]
ignore = ["ANN", "CPY", "D", "E501", "N801", "N999"]
preview = true
select = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 11
